Repository TeamHous/Hous-AosLab, pull requests merged in 2022-07, with the labels that each got.

#8 #14 [ui] home event dialog UI 구현
  app/src/main/res/drawable/ic_3d_example.xml
  app/src/main/res/drawable/iv_dialog_close.xml
  app/src/main/res/drawable/shape_basic_fill_10_rectangle.xml
  app/src/main/res/drawable/shape_red_line_10_rectangle.xml
  app/src/main/res/drawable/shape_yellow_fill_10_rectangle.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_dialog_event.xml
  app/src/main/res/layout/item_home_event_participant.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐻준원🐻, ui, pull request🔥

#6 #3 [ui] 홈 / 바텀네비게이션 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/housaoslab/HomeActivity.kt
  app/src/main/java/com/hous/housaoslab/MainActivity.kt
  app/src/main/res/color/sel_bot_nav_home_color.xml
  app/src/main/res/color/sel_bot_nav_profile_color.xml
  app/src/main/res/color/sel_bot_nav_rules_color.xml
  app/src/main/res/drawable/ic_white_fill_home.xml
  app/src/main/res/drawable/ic_white_fill_profile.xml
  app/src/main/res/drawable/ic_white_fill_rules.xml
  app/src/main/res/drawable/ic_white_line_home.xml
  app/src/main/res/drawable/ic_white_line_profile.xml
  app/src/main/res/drawable/ic_white_line_rules.xml
  app/src/main/res/drawable/sel_bot_nav_home.xml
  app/src/main/res/drawable/sel_bot_nav_profile.xml
  app/src/main/res/drawable/sel_bot_nav_rules.xml
  app/src/main/res/drawable/shape_blue_fill_30_rectangle.xml
  app/src/main/res/drawable/shape_red_fill_30_rectangle.xml
  app/src/main/res/drawable/shape_yellow_fill_30_rectangle.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/bot_nav.xml
Labels: 🐼영주🐼, ui, pull request🔥

#11 #10 [ui] 홈 / 툴바 구현
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/menu/bot_nav.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: 🐼영주🐼, ui, pull request🔥

#14 #12 [ui] 홈 / coming up 리사이클러뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/housaoslab/HomeActivity.kt
  app/src/main/java/com/hous/housaoslab/HomeFragment.kt
  app/src/main/java/com/hous/housaoslab/ui/home/MainActivity.kt
  app/src/main/java/com/hous/housaoslab/ui/home/model/ComingUpAdapter.kt
  app/src/main/java/com/hous/housaoslab/ui/home/model/ComingUpData.kt
  app/src/main/res/drawable/img_coming_up_party.png
  app/src/main/res/drawable/img_coming_up_plus.png
  app/src/main/res/drawable/shape_yellow_bg_fill_16_rectangle.xml
  app/src/main/res/drawable/shape_yellow_fill_16_rectangle.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_coming_up_detail.xml
  app/src/main/res/menu/bot_nav.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐼영주🐼, ui, pull request🔥

#21 #9 [feat] home_이벤트_추가_수정/ home뷰 다이얼로그 및 icon클릭 event처리
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hous/housaoslab/ui/home/event/EventDialogFragment.kt
  app/src/main/java/com/hous/housaoslab/ui/home/event/EventIcon.kt
  app/src/main/java/com/hous/housaoslab/ui/home/event/EventViewmodel.kt
  app/src/main/java/com/hous/housaoslab/ui/home/event/ExampleActivity.kt
  app/src/main/java/com/hous/housaoslab/util/BindingAdapter.kt
  app/src/main/java/com/hous/housaoslab/util/ListLiveDataUtil.kt
  app/src/main/java/com/hous/housaoslab/util/ToastUtil.kt
  app/src/main/res/drawable-v24/sel_item_event_pancake.xml
  app/src/main/res/drawable/ic_dialog_close.xml
  app/src/main/res/drawable/ic_dialog_pancake.png
  app/src/main/res/drawable/ic_dialog_party.png
  app/src/main/res/drawable/sel_item_event_party.xml
  app/src/main/res/layout/activity_example.xml
  app/src/main/res/layout/fragment_dialog_event.xml
Labels: 🐻준원🐻, feat, pull request🔥
